name: Tauri Rust Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: WebDriverIO Test Runner

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Tauri dependencies
        run: |
          sudo apt update && sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            webkit2gtk-driver \
            xvfb \
            libasound2-dev

      - name: Setup rust-toolchain stable
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo test
        run: cargo test
        working-directory: src-tauri

      - name: Cargo build
        run: cargo build --release
        working-directory: src-tauri

      - name: Install NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install --lts
          nvm use

      - name: Install Node.js via NVM
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install
          node --version
        working-directory: webdriver/webdriverio

      - name: Install NPM dependencies
        run: |
          nvm use
          npm install --ci
        working-directory: webdriver/webdriverio

      - name: Install tauri-driver
        run: cargo install tauri-driver --locked
        working-directory: src-tauri

      - name: Run WebDriverIO tests
        run: xvfb-run npm test
        working-directory: webdriver/webdriverio
